# Stage 1
FROM node:20-slim AS builder

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

# Stage 2: serve build
FROM node:20-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist

RUN npm install -g serve

CMD ["sh", "-c", "serve -s dist -l 80"]
