# Stage 1
FROM node:20-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

# Stage 2
FROM node:20-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist

RUN npm install -g serve

CMD ["sh", "-c", "serve -s dist -l 80"]
